#!/usr/bin/env node
// PreToolUse hook: denies edits to paths that a work branch must never write by hand.
//
// The playbook line this implements: a policy that must always hold needs something
// deterministic behind the advisory rule. Each entry below was written as prose first,
// in tests/README.md or .claude/rules/spec-loop.md, and prose fails silently — by the
// time a human notices, the agent has already seen a green gate and reported success.
const PROTECTED = [
  {
    match: /(^|\/)(tests?\/golden|sim\/baseline)\//,
    reason:
      "is a committed simulation snapshot; it is not edited by hand. " +
      'A red golden means "the simulation drifted": fix the code, not the snapshot. ' +
      "If the shift is intentional — regenerate it in its own pull request, one commit " +
      "prefixed golden: or baseline:, explaining which rule change moved the numbers " +
      "(tests/README.md).",
  },
  {
    match: /(^|\/)openspec\/specs\//,
    reason:
      "is the live behaviour layer. It is written by `openspec archive` merging a delta, " +
      "never by hand: a hand edit survives the whole gate and resurfaces months later as " +
      "a conflict during someone else's archive. Change the delta in " +
      "openspec/changes/<slug>/specs/ instead (docs/adr/0009).",
  },
  {
    match: /(^|\/)\.claude\/commands\/opsx\//,
    reason:
      "is generated by `openspec update --force` and any edit here disappears on the next " +
      "package update, silently. Extend the workflow through openspec/config.yaml — " +
      "`rules` and `operations.*.guidance` reach the agent through `openspec instructions` " +
      "(docs/adr/0009).",
  },
];

let raw = "";
for await (const chunk of process.stdin) raw += chunk;

let input;
try {
  input = JSON.parse(raw || "{}");
} catch {
  process.exit(0); // Couldn't parse the input — not our job to block.
}

const target = (input.tool_input?.file_path ?? input.tool_input?.notebook_path ?? "").replaceAll(
  "\\",
  "/",
);
const hit = PROTECTED.find((entry) => entry.match.test(target));
if (!hit) process.exit(0);

process.stdout.write(
  JSON.stringify({
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: `File ${target} ${hit.reason}`,
    },
  }),
);
